# Generated by Django 3.2 on 2021-04-30 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lit_app', '0002_student_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='TestSubmission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=30)),
                ('is_complete', models.BooleanField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lit_app.test')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('name', models.CharField(default=None, max_length=30)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('difficulty', models.IntegerField()),
                ('answer_blob', models.TextField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lit_app.test')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lit_app.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lit_app.student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lit_app.test')),
                ('test_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lit_app.testsubmission')),
            ],
        ),
    ]
