# Generated by Django 3.2 on 2021-05-01 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lit_app', '0003_auto_20210430_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsubmission',
            name='name',
        ),
        migrations.AddField(
            model_name='testsubmission',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='lit_app.student'),
        ),
        migrations.AlterField(
            model_name='testsubmission',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
