# Generated by Django 3.2 on 2021-05-01 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_app', '0003_auto_20210430_2113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='answer_blob',
            new_name='content',
        ),
    ]
