# Generated by Django 3.2 on 2021-05-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_app', '0004_auto_20210501_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsubmission',
            name='end_time',
            field=models.DateTimeField(default=None),
        ),
    ]
