# Generated by Django 3.2 on 2021-05-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_app', '0006_alter_testsubmission_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=models.TextField(default=None),
        ),
    ]
