# Generated by Django 3.2 on 2021-05-01 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit_app', '0004_rename_answer_blob_question_content'),
        ('lit_app', '0007_alter_answer_content'),
    ]

    operations = [
    ]
